#!/bin/bash
# GymTune Setup - Run this in your terminal

echo "🏋️ GymTune Setup"
echo "================"
echo ""
echo "Run these commands in your terminal:"
echo ""
echo "# 1. Install GitHub CLI (requires sudo)"
echo "curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
echo "sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg"
echo "echo \"deb [arch=\$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null"
echo "sudo apt update && sudo apt install gh -y"
echo ""
echo "# 2. Authenticate with GitHub"
echo "gh auth login"
echo ""
echo "# 3. Push code to GitHub"
echo "git push -u origin main"
echo ""
echo "# 4. Create issues"
echo "./scripts/create-issues.sh"
echo ""
echo "Or just run:"
echo "./scripts/setup-repo.sh"
